version: '3'
services:
  td-agent:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        - ARG_AWS_S3_ACCESS_KEY_ID=$DOTENV_AWS_S3_ACCESS_KEY_ID
        - ARG_AWS_S3_SCRET_ACCESS_KEY=$DOTENV_AWS_S3_SCRET_ACCESS_KEY
        - ARG_AWS_S3_BUCKET=$DOTENV_AWS_S3_BUCKET
        - ARG_AWS_S3_REGION=$DOTENV_AWS_S3_REGION
        - ARG_AWS_S3_PATH=$DOTENV_AWS_S3_PATH
    environment:
      - TZ=Asia/Tokyo
    ports:
      - "8888:8888"
      - "514:514/udp"
    tty: true
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    tmpfs:
      - /run
      - /tmp
    stop_signal: SIGRTMIN+3
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
